name: "Build Docker Image"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Dependencies
        run: yarn install
      - name: Build code
        run: yarn build
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          registry: docker.pkg.github.com
          repository: Code-Hex/auto-milestone-binder/auto-milestone-binder
          tag_with_ref: true