
on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ku/auto-milestone-binder@v1.1.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        loose: '1'
