name: "Test code"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Dependencies
        run: yarn install
      - name: Run test
        run: yarn test
